version: "3.8"

x-postgres_environment: &postgres_environment
  POSTGRES_DB: ${POSTGRES_DB:-postgres}
  POSTGRES_USER: ${POSTGRES_USER:-postgres}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
  POSTGRES_HOST: ${POSTGRES_HOST:-db}
  POSTGRES_PORT: ${POSTGRES_PORT:-5432}

services:
  backend:
    container_name: test_task_backend
    build:
      context: backend
    command: uvicorn src.api.main:app --reload --host 0.0.0.0 --port 80
    volumes:
      - ./backend:/app
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      <<: *postgres_environment

  db:
    image: docker.io/postgres:13-alpine
    hostname: db
    container_name: db
    environment:
      <<: *postgres_environment
